[behave]
paths = src/features
format=allure_behave.formatter:AllureFormatter
outfiles=allure-results
use_nested_step_modules = true

[behave.userdata]
#chrome, firefox, chromium, edge, safari
browser = chromium
test_id_attribute = data-test

#desktop, mobile
browser_platform = desktop


#Global execution mode: api / hybrid or leave blank for default (UI)
execution_mode = hybrid

environment = dev

dev = https://parabank.parasoft.com/parabank/index.htm
prod = https://parabank.parasoft.com/parabank/index.htm

# API URLs
# Keep trailing slash so relative endpoints like "accounts/24666" resolve under /services/bank/
api_dev = https://parabank.parasoft.com/parabank/services/bank/
api_prod= https://parabank.parasoft.com/parabank/services/bank/

octane = false